FROM gcc:11

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      bison \
      cmake \
      flex \
      libgmp3-dev \
      libgtest-dev \
      libopenmpi-dev \
      openmpi-bin \
      openmpi-common \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/jeetsukumaran/DendroPy.git \
 && cd DendroPy \
 && python setup.py install \
 && cd .. \
 && rm -rf DendroPy
 