FROM gcc:7.5

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      bison \
      cmake \
      flex \
      libgmp3-dev \
      libgtest-dev \
      libopenmpi-dev \
      openmpi-bin \
      openmpi-common \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/jeetsukumaran/DendroPy.git \
 && cd DendroPy \
 && python3 setup.py install \
 && cd .. \
 && rm -rf DendroPy
 
RUN git clone https://github.com/BerndDoser/raxml-ng.git \
 && cd raxml-ng \
 && git checkout ci \
 && git submodule update --init --recursive \
 && git submodule add https://github.com/amkozlov/ngtest.git \
 && mkdir -p build \
 && cd build \
 && cmake -DCMAKE_BUILD_TYPE=Release -DUSE_MPI=ON .. 2>&1 |tee cmake.out \
 && make 2>&1 |tee make.out
